#' Synthetic multi-level indoor features in local coordinates
#'
#' A synthetic, freely reusable indoor plan created for package examples and
#' tests. It does not describe a real building. The mixed `sf` object contains
#' points, lines, polygons, and multiple geometries. Its `level` list-column
#' includes an elevator and stairs assigned to several floors.
#'
#' @format An `sf` object with 10 features and 7 variables:
#' \describe{
#'   \item{feature_id}{Stable synthetic feature identifier.}
#'   \item{name}{Short feature label.}
#'   \item{description}{Popup-ready description.}
#'   \item{kind}{Feature category.}
#'   \item{fill}{Suggested fill color.}
#'   \item{level}{List-column of floor values.}
#'   \item{geometry}{Local Cartesian geometry with an undefined CRS.}
#' }
#' @source Generated by `data-raw/indoor_demo.R`.
"indoor_demo"

#' Synthetic multi-level indoor features in geographic coordinates
#'
#' A geographic companion to [indoor_demo], constructed directly in
#' EPSG:4326 for offline examples. It is synthetic and does not describe a real
#' building.
#'
#' @format An `sf` object with the same attributes and geometry types as
#'   [indoor_demo], using EPSG:4326.
#' @source Generated by `data-raw/indoor_demo.R`.
"indoor_demo_geo"
